venera-app/venera-configs

picacg.js
=> fix: the episode list on Picacg is in the wrong order

ehentai.js
=> ehentai: handle thumbnail labeling again

ehentai.js
Extended mode 下有 gt gtl 两种 tag
=> ehentai: improve page display

ehentai.js
=> ehentai: fix folders

ehentai.js
=> ehentai: webp

ehentai.js
=> eh: handle warning

copy_manga.js, index.json
=> [copy]fix theme

index.json, jm.js
jm 首页 响应中 “禁漫書庫” 的部分目前有问题，跳过这里。
=> jm: skip parsing type library

ehentai.js, index.json
fix https://github.com/venera-app/venera/issues/134
Compact 模式下 explore 页与 favorite 页布局不同。
=> eh: DOM: fix gallery page count in favorite page

index.json, jm.js
=> jm: update version code, domain and UA

index.json, jm.js
=> jm: support domain-updating API

ikmmh.js
=> fix ikmmh.js

wnacg.js
=> fix wnacg.js

copy_manga.js, index.json
mangacopy.com is currently inaccessible in mainland China.
=> [copy_manga] Update copyVersion && Allow user to edit apiUrl

copy_manga.js, index.json
=> [copy_manga] Allow user to edit copyPlatform 

copy_manga.js, index.json
=> [copy_manga] Add configurable image quality and CDN region options for CopyManga

index.json, shonenjumpplus.js
**features**:
- Use Mobile GraphQL API
- No Need To Login: Extension use a random device id for authorization each time.
- Unlimit Renting Chapters: Each time refreshing a new device id, we can get new 100 points for renting new chapters free.
=> [shonen_jump_plus] add shonen jump plus

copy_manga.js, index.json
@lings03 
https://github.com/venera-app/venera-configs/pull/78#issuecomment-2938010870
=> [copy_manga] Remove validator in copyVersion

hitomi.js
修复：在onClickTag方法中缺少对namespace的验证和修改。
=> fix bug in hitomi.js

index.json, shonenjumpplus.js
According to the error message: `{"error_code":"UPDATE_REQUIRED","message":"アプリのアップデートが必要です"}`, the app version in User-Agent needs to be update.
=> [shonen_jump_plus] Update User-Agent

copy_manga.js, index.json
base api应该能用了
web api会自动获取网站最新的api
=> [copy_manga] Fix search api (base & web)

baihehui.js, comick.js, index.json
- Multi-language comic selection support
- Added comic recommendations
- Fixed empty chapter bringing error
- Resolved tag click issues
- Optimized data processing
new source from baihehui
=> Add new function for comick resource

nhentai.js
- 利用 nhentai.net/api/galleries/tagged?tag_id 来获取tags的正确总数
以下tags词可用于category，parody，groups，author等等
旧方法只能用于search (search 是 xxx result)，但有些tags就不能 (抓取时是 10k, 5k, 1k，只有少于1k一下才能抓取正确的总数)
新方法的唯一缺点是很迷的status 403，tag_id=127065为例子，如果试50次可能只有1次成功。但是其他的tags就能稳定读取。
- 在search option的”-Recent“加上"&"，以能正常sorting
没加&的时候顺序混乱，加了后就会从最新开始（可看n号判断）
=> Fix nhentai search method & fix search sorting

baihehui.js, comick.js, index.json
Fixed the issue where some comic info pages couldn't retrieve chapters and update times.
Added 4 sorting methods for comics in the category page.
=> Fixed some bugs and added some sorting methods(category page) in comick

ikmmh.js, index.json
=> fix: 更新爱看漫插件版本至1.0.3

ehentai.js, index.json, nhentai.js
=> eh&nh: fix url open

hitomi.js, index.json
- Fixed a bug where results could conflict when multiple searches occur simultaneously.
- Fixed a bug where incorrect titles appeared during category browsing.
=> [hitomi.la] bugfix

ikmmh.js, index.json
添加绕过反爬方法，修复unexpected token错误
域名使用www.ikmmh.com，ymcdnyfqdapp.ikmmh.com这个域名有时候解析不了
=> [ikmmh] Add pass validator

index.json
=> 更新 index.json 版本号 更新少年漫版本号 #161 禁漫版本号#163  ，删除重复的优酷

jm.js
在远程源res添加了try，防止目标访问不了直接抛弃而无法进入fallback
=> 接上一个pr的版本号，修复禁漫远程源fallback
